=== OmarGamal07/ITI/xml/lab1/lab1.dtd
<?xml version="1.0" encoding="UTF-8"?><!ELEMENT iti-branch (Trainee)+><!ELEMENT Trainee  (name, addrees , phone+,course-result+)><!ATTLIST Trainee   group (group1|group2) #REQUIRED   age CDATA #IMPLIED > <!ELEMENT name (#PCDATA)><!ELEMENT addrees EMPTY><!ATTLIST addrees   governorate CDATA #IMPLIED   street CDATA #IMPLIED   zipcode CDATA #IMPLIED   ><!ELEMENT phone (#PCDATA)><!ELEMENT course-result (course-name)><!ELEMENT course-name (#PCDATA)><!ATTLIST course-result    grade (A|B|C|D|E) #REQUIRED >

=== OmarGamal07/ITI/xml/lab1/Untitled8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE  iti-branch SYSTEM "E:\open soure\xml\lab1\lab1.dtd" >
<iti-branch>
<Trainee group="group1" age="18">
<name>omar</name>
<addrees governorate="assuit" street="sd" zipcode="8"></addrees>
<phone>011568489</phone>
<phone>051689489</phone>
<course-result grade="A">
<course-name>xml</course-name>
</course-result>
</Trainee>
</iti-branch>
